name : Django Techeria Tests

on:
  push:
    branches:
      - main

  pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: echo "RUNNING TESTS"
